spring.application.name=ssts-integrated-webapp
spring.thymeleaf.cache=false
server.port=${PORT:8081}

# PostgreSQL configuration
# spring.datasource.url=jdbc:postgresql://${DB_HOST:dpg-dappla49v7es739g7rrg-a}:${DB_PORT:5432}/${DB_NAME:ssts_pr}
spring.datasource.url=jdbc:postgresql://dpg-dappla49v7es739g7rrg-a.oregon-postgres.render.com:5432/ssts_pr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=ssts_admin
spring.datasource.password=9iXw4Xu9V2OGcAdJFWLle6V1mkIB0os7
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.show-sql=${DB_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=${DB_FORMAT_SQL:true}